query allJobs {
  jobs {
    id
    title
    company {
      id
      name
      logoUrl
    }
    cities {
      id
      name
    }
    remotes {
      id
      name
      type
    }
    tags {
      id
      name
    }
  }
}
